            <!-- Right side column. Contains the navbar and content of the page -->            <aside class="right-side">                <!-- Content Header (Page header) -->                <section class="content-header">                    <h1>Users / <small>View All Users</small></h1>                    <ol class="breadcrumb">                        <li><a href="<?php echo base_url()?>index.php/admin/home"><i class="fa fa-dashboard"></i> Go back to dashboard</a></li>                    </ol>                </section>                <!-- Main content -->                <section class="content">                    <div class="box">						<div class="box-header">
                            <h3 class="box-title">View All Users &nbsp;
                                <a href="<?php echo base_url()?>index.php/admin/users/create_user" class="btn btn-primary btn-sm">Create New User</a>
                                <input type="button" id="delete_seleted_users" class="btn btn-danger btn-sm" value="Delete Selected"/></h3>						</div><!-- /.box-header -->						<div class="box-body table-responsive">							<table id="tbl-propertiesForSale" class="table table-bordered table-striped">								<thead>									<tr>										<th>											<div class="checkbox">												<input type="checkbox"/>											</div>										</th>										<th>User ID</th>										<th>Full Name</th>										<th>Registered On</th>										<th>Properties</th>										<th>Status</th>										<th>Actions</th>									</tr>								</thead>								<tbody>                                                                <?php foreach($query as $row) {								if($row->status == 1)								{									$status = "Active";									$action = "<a href='http://uzairusman.com/hp/index.php/admin/users/deactuser/$row->user_id'><i class='fa fa-ban'></i> Deactivate</a>";								}								else								{									$status = "Inactive";									$action = "<a href='http://uzairusman.com/hp/index.php/admin/users/actuser/$row->user_id'><i class='fa fa-green fa-check'></i> Activate</a>";																		}									?>									<tr>										<td valign="middle">											<div class="checkbox">												<input type="checkbox"/>											</div>										</td>
                                    <td valign="middle"><a href="sales-invoice.php"><?php echo $row->user_id?></a></td>
                                    <td valign="middle"><a href="#"><?php echo $row->user_name?></a></td>
                                    <td valign="middle"><?php echo $row->registration_date?></td>
                                    <td valign="middle"><a href="<?php echo base_url()?>index.php/admin/property/userprop/<?php echo $row->user_id?>"><?php echo $this->common->countprop($row->user_id)?> properties</a></td>
                                    <td valign="middle"><?php echo $status?></td>
                                    <td valign="middle" class="actions" ><a href="<?php echo base_url()?>index.php/admin/users/edit_user/<?php echo $row->user_id?>"><i class="fa fa-yellow fa-pencil"></i> Edit</a>&nbsp;&nbsp;&nbsp; <a class="delete_opt" href="<?php echo base_url()?>index.php/admin/users/delete/<?php echo $row->user_id?>"><i class="fa fa-times"></i> Delete</a>&nbsp;&nbsp;&nbsp; <a href="<?php echo base_url()?>index.php/admin/property/add_property_user/<?php echo $row->user_id?>"><i class="fa fa-plus-square"></i> Add Property </a>&nbsp;&nbsp;&nbsp; <?php echo $action?></td>									</tr>                                    <?php } ?>							</tbody>								<tfoot>									<tr>										<th>											<div class="checkbox">												<input type="checkbox"/>											</div>										</th>										<th>User ID</th>										<th>Full Name</th>										<th>Registered On</th>										<th>Properties</th>										<th>Status</th>										<th>Actions</th>									</tr>								</tfoot>							</table>						</div><!-- /.box-body -->					</div>                </section><!-- /.content -->            </aside><!-- /.right-side -->        </div><!-- ./wrapper -->